### ISSUE TITLE
Will brainliner.jp be accessed normally soon?

### ISSUE THREAD

**Issue by dlmdlmacy** [KamitaniLab/HumanDreamDecoding#1]
Hello!

Thank you for your excellent job! I'm doing a research using the data on http://brainliner.jp/. However, when I tried to access this website, I got a 502 error. So I really want to know that will this website return to normal soon? Or it stops service?

Thank you for your replies! Have a good day!

Yours,
dlmdlmacy

**Comment by ShuntaroAoki** [comment]
I apologise for the inconvenience. Now I'm working with admins to fix the issue. We're also working on releasing the dream decoding data at figshare. I'll let you know when the data get available again.

**Comment by ShuntaroAoki** [comment]
We've fixed the issue on brainliner.jp. Now you can access and download the data.

**Comment by dlmdlmacy** [comment]
Thank you SOOOOOOOOOOOOOOOOOOO much! It can be accessed normally.
